public enum EventID
{
    SPAWNING_PLAYER,
    INITIALIZING_ALL_PLAYER_LIST,
    SETTED_UP_GAMEPLAY,
    CATCHING_PLAYER,
    SPOTTED_OBJECT,
    SETTED_UP_PLAYER_ROLE,
    CAUGHT_HIDER,
    RESCUING_HIDER,
    END_HIDING_TIME,
}